services:
  ebisu:
    build: ./
    ports:
      - "${PORT}:8765"
    restart: always

  db:
    image: postgres:13
    ports:
      - "32000:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ebisu